apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7  # Use the MySQL version you prefer
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"  # Set your MySQL root password
            - name: MYSQL_DATABASE
              value: "mydb"  # Create a database at startup
          ports:
            - containerPort: 3306