apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: manigowtham08/testing:latest
        ports:
        - containerPort: 8000
          env:
            - name: DB_USER
              value: "root"  # MySQL root user
            - name: DB_PASSWORD
              value: "root"  # MySQL root password
            - name: DB_HOST
              value: "mysql-service"  # MySQL service name
            - name: DB_DATABASE
              value: "mydb"  